image: gcc

build:
  stage: build
  before_script:
    - apt-get -qq update && apt-get -qq -y install cmake
  script:
    - mkdir build && cd build
    - cmake ..
    - make
  artifacts:
    paths:
    - build/

test:
  stage: test
  dependencies:
    - build
  before_script:
    - apt-get -qq update && apt-get -qq -y install cmake
  script:
    - cd build
    - ctest --verbose

variables:
  GIT_SUBMODULE_STRATEGY: recursive

